SELECT * FROM TRABALHOFINAL.TBFORNECEDORES
SELECT * FROM TRABALHOFINAL.TBCLIENTES
SELECT * FROM TRABALHOFINAL.TBPRODUTOS
SELECT * FROM TRABALHOFINAL.TBCATEGORIA
SELECT * FROM TRABALHOFINAL.TBUSUARIOS
